### ISSUE TITLE
Issues with | changed on ansible 2.9~

### ISSUE THREAD

**Issue by danielsimkus** [nickjj/ansible-swapfile#3]
Getting errors on the latest ansible version with the conditional check:
```
- name: Initialize swap file
  command: mkswap {{ swapfile_path }}
  when: (swapfile_register_create | changed and not swapfile_delete)
```

Reverting to ansible version 2.8.6 fixes the issue.

**Comment by nickjj** [comment]
Hi,

Does it work with 2.9 if you use `when: (swapfile_register_create is changed and not swapfile_delete)`?

**Comment by danielsimkus** [comment]
Yeah that's fixed it 👍

**Comment by danielsimkus** [comment]
I'm closing this issue, as the current version is actually fixed, I think Galaxy just needs updating as that still gets the old version.

**Comment by hudecof** [comment]
@nickjj please, do new relelase, the bug was already fixed  in #1 
otherwise we need to fork this

**Comment by nickjj** [comment]
I will try to cut a release soon.

It's not that simple because for the last ~9 months I've been slowly working on refactoring and updating all of my roles. The current incarnation of this role is quite a bit different now (although it's generally the same so upgrading won't be too bad).

I'll see what I can do today because it will involve releasing a new role and updating this one drastically.

**Comment by hudecof** [comment]
as a quick fix is just to add tag to current master on github and  force galaxy to update

**Comment by nickjj** [comment]
And also updating the changelog. But yeah, I just made the release as v0.2.0 with just this compatibility change. It's up on the Galaxy.
